// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AmazontoWorld.proto

package edu.duke.ece568.minUPS.protocol.AmazontoWorld;

public interface AInitWarehouseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AInitWarehouse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>required int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>required int32 x = 2;</code>
   */
  boolean hasX();
  /**
   * <code>required int32 x = 2;</code>
   */
  int getX();

  /**
   * <code>required int32 y = 3;</code>
   */
  boolean hasY();
  /**
   * <code>required int32 y = 3;</code>
   */
  int getY();
}
