// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AmazontoWorld.proto

package edu.duke.ece568.minUPS.protocol.AmazontoWorld;

public interface ALoadedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ALoaded)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 shipid = 1;</code>
   */
  boolean hasShipid();
  /**
   * <code>required int64 shipid = 1;</code>
   */
  long getShipid();

  /**
   * <code>required int64 seqnum = 2;</code>
   */
  boolean hasSeqnum();
  /**
   * <code>required int64 seqnum = 2;</code>
   */
  long getSeqnum();
}
