// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AmazontoWorld.proto

package edu.duke.ece568.minUPS.protocol.AmazontoWorld;

public interface APackOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 whnum = 1;</code>
   */
  boolean hasWhnum();
  /**
   * <code>required int32 whnum = 1;</code>
   */
  int getWhnum();

  /**
   * <code>repeated .AProduct things = 2;</code>
   */
  java.util.List<edu.duke.ece568.minUPS.protocol.AmazontoWorld.AProduct> 
      getThingsList();
  /**
   * <code>repeated .AProduct things = 2;</code>
   */
  edu.duke.ece568.minUPS.protocol.AmazontoWorld.AProduct getThings(int index);
  /**
   * <code>repeated .AProduct things = 2;</code>
   */
  int getThingsCount();
  /**
   * <code>repeated .AProduct things = 2;</code>
   */
  java.util.List<? extends edu.duke.ece568.minUPS.protocol.AmazontoWorld.AProductOrBuilder> 
      getThingsOrBuilderList();
  /**
   * <code>repeated .AProduct things = 2;</code>
   */
  edu.duke.ece568.minUPS.protocol.AmazontoWorld.AProductOrBuilder getThingsOrBuilder(
      int index);

  /**
   * <code>required int64 shipid = 3;</code>
   */
  boolean hasShipid();
  /**
   * <code>required int64 shipid = 3;</code>
   */
  long getShipid();

  /**
   * <code>required int64 seqnum = 4;</code>
   */
  boolean hasSeqnum();
  /**
   * <code>required int64 seqnum = 4;</code>
   */
  long getSeqnum();
}
