// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AmazontoWorld.proto

package edu.duke.ece568.minUPS.protocol.AmazontoWorld;

public interface APackageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APackage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 packageid = 1;</code>
   */
  boolean hasPackageid();
  /**
   * <code>required int64 packageid = 1;</code>
   */
  long getPackageid();

  /**
   * <code>required string status = 2;</code>
   */
  boolean hasStatus();
  /**
   * <code>required string status = 2;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>required string status = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>required int64 seqnum = 3;</code>
   */
  boolean hasSeqnum();
  /**
   * <code>required int64 seqnum = 3;</code>
   */
  long getSeqnum();
}
