// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AmazontoWorld.proto

package edu.duke.ece568.minUPS.protocol.AmazontoWorld;

public interface AProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AProduct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>required int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>required string description = 2;</code>
   */
  boolean hasDescription();
  /**
   * <code>required string description = 2;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>required string description = 2;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>required int32 count = 3;</code>
   */
  boolean hasCount();
  /**
   * <code>required int32 count = 3;</code>
   */
  int getCount();
}
