// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AmazontoWorld.proto

package edu.duke.ece568.minUPS.protocol.AmazontoWorld;

/**
 * Protobuf type {@code APutOnTruck}
 */
public  final class APutOnTruck extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:APutOnTruck)
    APutOnTruckOrBuilder {
private static final long serialVersionUID = 0L;
  // Use APutOnTruck.newBuilder() to construct.
  private APutOnTruck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private APutOnTruck() {
    whnum_ = 0;
    truckid_ = 0;
    shipid_ = 0L;
    seqnum_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.duke.ece568.minUPS.protocol.AmazontoWorld.AmazontoWorld.internal_static_APutOnTruck_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.duke.ece568.minUPS.protocol.AmazontoWorld.AmazontoWorld.internal_static_APutOnTruck_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck.class, edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck.Builder.class);
  }

  private int bitField0_;
  public static final int WHNUM_FIELD_NUMBER = 1;
  private int whnum_;
  /**
   * <code>required int32 whnum = 1;</code>
   */
  public boolean hasWhnum() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int32 whnum = 1;</code>
   */
  public int getWhnum() {
    return whnum_;
  }

  public static final int TRUCKID_FIELD_NUMBER = 2;
  private int truckid_;
  /**
   * <code>required int32 truckid = 2;</code>
   */
  public boolean hasTruckid() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required int32 truckid = 2;</code>
   */
  public int getTruckid() {
    return truckid_;
  }

  public static final int SHIPID_FIELD_NUMBER = 3;
  private long shipid_;
  /**
   * <code>required int64 shipid = 3;</code>
   */
  public boolean hasShipid() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required int64 shipid = 3;</code>
   */
  public long getShipid() {
    return shipid_;
  }

  public static final int SEQNUM_FIELD_NUMBER = 4;
  private long seqnum_;
  /**
   * <code>required int64 seqnum = 4;</code>
   */
  public boolean hasSeqnum() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>required int64 seqnum = 4;</code>
   */
  public long getSeqnum() {
    return seqnum_;
  }

  public static edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code APutOnTruck}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:APutOnTruck)
      edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruckOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.duke.ece568.minUPS.protocol.AmazontoWorld.AmazontoWorld.internal_static_APutOnTruck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.duke.ece568.minUPS.protocol.AmazontoWorld.AmazontoWorld.internal_static_APutOnTruck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck.class, edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck.Builder.class);
    }

    // Construct using edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      whnum_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      truckid_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      shipid_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      seqnum_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.duke.ece568.minUPS.protocol.AmazontoWorld.AmazontoWorld.internal_static_APutOnTruck_descriptor;
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck getDefaultInstanceForType() {
      return edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck.getDefaultInstance();
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck build() {
      edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck buildPartial() {
      edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck result = new edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.whnum_ = whnum_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.truckid_ = truckid_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.shipid_ = shipid_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.seqnum_ = seqnum_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    private int bitField0_;

    private int whnum_ ;
    /**
     * <code>required int32 whnum = 1;</code>
     */
    public boolean hasWhnum() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 whnum = 1;</code>
     */
    public int getWhnum() {
      return whnum_;
    }
    /**
     * <code>required int32 whnum = 1;</code>
     */
    public Builder setWhnum(int value) {
      bitField0_ |= 0x00000001;
      whnum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 whnum = 1;</code>
     */
    public Builder clearWhnum() {
      bitField0_ = (bitField0_ & ~0x00000001);
      whnum_ = 0;
      onChanged();
      return this;
    }

    private int truckid_ ;
    /**
     * <code>required int32 truckid = 2;</code>
     */
    public boolean hasTruckid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 truckid = 2;</code>
     */
    public int getTruckid() {
      return truckid_;
    }
    /**
     * <code>required int32 truckid = 2;</code>
     */
    public Builder setTruckid(int value) {
      bitField0_ |= 0x00000002;
      truckid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 truckid = 2;</code>
     */
    public Builder clearTruckid() {
      bitField0_ = (bitField0_ & ~0x00000002);
      truckid_ = 0;
      onChanged();
      return this;
    }

    private long shipid_ ;
    /**
     * <code>required int64 shipid = 3;</code>
     */
    public boolean hasShipid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 shipid = 3;</code>
     */
    public long getShipid() {
      return shipid_;
    }
    /**
     * <code>required int64 shipid = 3;</code>
     */
    public Builder setShipid(long value) {
      bitField0_ |= 0x00000004;
      shipid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 shipid = 3;</code>
     */
    public Builder clearShipid() {
      bitField0_ = (bitField0_ & ~0x00000004);
      shipid_ = 0L;
      onChanged();
      return this;
    }

    private long seqnum_ ;
    /**
     * <code>required int64 seqnum = 4;</code>
     */
    public boolean hasSeqnum() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 seqnum = 4;</code>
     */
    public long getSeqnum() {
      return seqnum_;
    }
    /**
     * <code>required int64 seqnum = 4;</code>
     */
    public Builder setSeqnum(long value) {
      bitField0_ |= 0x00000008;
      seqnum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 seqnum = 4;</code>
     */
    public Builder clearSeqnum() {
      bitField0_ = (bitField0_ & ~0x00000008);
      seqnum_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:APutOnTruck)
  }

  // @@protoc_insertion_point(class_scope:APutOnTruck)
  private static final edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck();
  }

  public static edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<APutOnTruck>
      PARSER = new com.google.protobuf.AbstractParser<APutOnTruck>() {
    @java.lang.Override
    public APutOnTruck parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(
                builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<APutOnTruck> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<APutOnTruck> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.AmazontoWorld.APutOnTruck getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

