// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AmazontoWorld.proto

package edu.duke.ece568.minUPS.protocol.AmazontoWorld;

public interface APutOnTruckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APutOnTruck)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 whnum = 1;</code>
   */
  boolean hasWhnum();
  /**
   * <code>required int32 whnum = 1;</code>
   */
  int getWhnum();

  /**
   * <code>required int32 truckid = 2;</code>
   */
  boolean hasTruckid();
  /**
   * <code>required int32 truckid = 2;</code>
   */
  int getTruckid();

  /**
   * <code>required int64 shipid = 3;</code>
   */
  boolean hasShipid();
  /**
   * <code>required int64 shipid = 3;</code>
   */
  long getShipid();

  /**
   * <code>required int64 seqnum = 4;</code>
   */
  boolean hasSeqnum();
  /**
   * <code>required int64 seqnum = 4;</code>
   */
  long getSeqnum();
}
