// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AmazontoWorld.proto

package edu.duke.ece568.minUPS.protocol.AmazontoWorld;

public interface AQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 packageid = 1;</code>
   */
  boolean hasPackageid();
  /**
   * <code>required int64 packageid = 1;</code>
   */
  long getPackageid();

  /**
   * <code>required int64 seqnum = 2;</code>
   */
  boolean hasSeqnum();
  /**
   * <code>required int64 seqnum = 2;</code>
   */
  long getSeqnum();
}
