// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: withAmazon.proto

package edu.duke.ece568.minUPS.protocol.UPStoAmazon;

/**
 * Protobuf type {@code tutorial.ABookTruck}
 */
public  final class ABookTruck extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.ABookTruck)
    ABookTruckOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ABookTruck.newBuilder() to construct.
  private ABookTruck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ABookTruck() {
    packageid_ = 0L;
    warehouseid_ = 0;
    warehousex_ = 0;
    warehousey_ = 0;
    destinationx_ = 0;
    destinationy_ = 0;
    upsid_ = "";
    seqnum_ = 0L;
    detail_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.duke.ece568.minUPS.protocol.UPStoAmazon.WithAmazon.internal_static_tutorial_ABookTruck_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.duke.ece568.minUPS.protocol.UPStoAmazon.WithAmazon.internal_static_tutorial_ABookTruck_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.class, edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.Builder.class);
  }

  private int bitField0_;
  public static final int PACKAGEID_FIELD_NUMBER = 1;
  private long packageid_;
  /**
   * <code>required int64 packageid = 1;</code>
   */
  public boolean hasPackageid() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int64 packageid = 1;</code>
   */
  public long getPackageid() {
    return packageid_;
  }

  public static final int WAREHOUSEID_FIELD_NUMBER = 2;
  private int warehouseid_;
  /**
   * <code>required int32 warehouseid = 2;</code>
   */
  public boolean hasWarehouseid() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required int32 warehouseid = 2;</code>
   */
  public int getWarehouseid() {
    return warehouseid_;
  }

  public static final int WAREHOUSEX_FIELD_NUMBER = 3;
  private int warehousex_;
  /**
   * <code>required int32 warehousex = 3;</code>
   */
  public boolean hasWarehousex() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required int32 warehousex = 3;</code>
   */
  public int getWarehousex() {
    return warehousex_;
  }

  public static final int WAREHOUSEY_FIELD_NUMBER = 4;
  private int warehousey_;
  /**
   * <code>required int32 warehousey = 4;</code>
   */
  public boolean hasWarehousey() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>required int32 warehousey = 4;</code>
   */
  public int getWarehousey() {
    return warehousey_;
  }

  public static final int DESTINATIONX_FIELD_NUMBER = 5;
  private int destinationx_;
  /**
   * <code>required int32 destinationx = 5;</code>
   */
  public boolean hasDestinationx() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>required int32 destinationx = 5;</code>
   */
  public int getDestinationx() {
    return destinationx_;
  }

  public static final int DESTINATIONY_FIELD_NUMBER = 6;
  private int destinationy_;
  /**
   * <code>required int32 destinationy = 6;</code>
   */
  public boolean hasDestinationy() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>required int32 destinationy = 6;</code>
   */
  public int getDestinationy() {
    return destinationy_;
  }

  public static final int UPSID_FIELD_NUMBER = 7;
  private volatile java.lang.Object upsid_;
  /**
   * <code>optional string upsid = 7;</code>
   */
  public boolean hasUpsid() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional string upsid = 7;</code>
   */
  public java.lang.String getUpsid() {
    java.lang.Object ref = upsid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        upsid_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string upsid = 7;</code>
   */
  public com.google.protobuf.ByteString
      getUpsidBytes() {
    java.lang.Object ref = upsid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      upsid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEQNUM_FIELD_NUMBER = 8;
  private long seqnum_;
  /**
   * <code>optional int64 seqnum = 8;</code>
   */
  public boolean hasSeqnum() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>optional int64 seqnum = 8;</code>
   */
  public long getSeqnum() {
    return seqnum_;
  }

  public static final int DETAIL_FIELD_NUMBER = 9;
  private volatile java.lang.Object detail_;
  /**
   * <code>optional string detail = 9;</code>
   */
  public boolean hasDetail() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>optional string detail = 9;</code>
   */
  public java.lang.String getDetail() {
    java.lang.Object ref = detail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        detail_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string detail = 9;</code>
   */
  public com.google.protobuf.ByteString
      getDetailBytes() {
    java.lang.Object ref = detail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      detail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tutorial.ABookTruck}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.ABookTruck)
      edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruckOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.duke.ece568.minUPS.protocol.UPStoAmazon.WithAmazon.internal_static_tutorial_ABookTruck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.duke.ece568.minUPS.protocol.UPStoAmazon.WithAmazon.internal_static_tutorial_ABookTruck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.class, edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.Builder.class);
    }

    // Construct using edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      packageid_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      warehouseid_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      warehousex_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      warehousey_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      destinationx_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      destinationy_ = 0;
      bitField0_ = (bitField0_ & ~0x00000020);
      upsid_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      seqnum_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000080);
      detail_ = "";
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.duke.ece568.minUPS.protocol.UPStoAmazon.WithAmazon.internal_static_tutorial_ABookTruck_descriptor;
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck getDefaultInstanceForType() {
      return edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck.getDefaultInstance();
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck build() {
      edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck buildPartial() {
      edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck result = new edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.packageid_ = packageid_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.warehouseid_ = warehouseid_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.warehousex_ = warehousex_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.warehousey_ = warehousey_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.destinationx_ = destinationx_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.destinationy_ = destinationy_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.upsid_ = upsid_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      result.seqnum_ = seqnum_;
      if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
        to_bitField0_ |= 0x00000100;
      }
      result.detail_ = detail_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    private int bitField0_;

    private long packageid_ ;
    /**
     * <code>required int64 packageid = 1;</code>
     */
    public boolean hasPackageid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 packageid = 1;</code>
     */
    public long getPackageid() {
      return packageid_;
    }
    /**
     * <code>required int64 packageid = 1;</code>
     */
    public Builder setPackageid(long value) {
      bitField0_ |= 0x00000001;
      packageid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 packageid = 1;</code>
     */
    public Builder clearPackageid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      packageid_ = 0L;
      onChanged();
      return this;
    }

    private int warehouseid_ ;
    /**
     * <code>required int32 warehouseid = 2;</code>
     */
    public boolean hasWarehouseid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 warehouseid = 2;</code>
     */
    public int getWarehouseid() {
      return warehouseid_;
    }
    /**
     * <code>required int32 warehouseid = 2;</code>
     */
    public Builder setWarehouseid(int value) {
      bitField0_ |= 0x00000002;
      warehouseid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 warehouseid = 2;</code>
     */
    public Builder clearWarehouseid() {
      bitField0_ = (bitField0_ & ~0x00000002);
      warehouseid_ = 0;
      onChanged();
      return this;
    }

    private int warehousex_ ;
    /**
     * <code>required int32 warehousex = 3;</code>
     */
    public boolean hasWarehousex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 warehousex = 3;</code>
     */
    public int getWarehousex() {
      return warehousex_;
    }
    /**
     * <code>required int32 warehousex = 3;</code>
     */
    public Builder setWarehousex(int value) {
      bitField0_ |= 0x00000004;
      warehousex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 warehousex = 3;</code>
     */
    public Builder clearWarehousex() {
      bitField0_ = (bitField0_ & ~0x00000004);
      warehousex_ = 0;
      onChanged();
      return this;
    }

    private int warehousey_ ;
    /**
     * <code>required int32 warehousey = 4;</code>
     */
    public boolean hasWarehousey() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 warehousey = 4;</code>
     */
    public int getWarehousey() {
      return warehousey_;
    }
    /**
     * <code>required int32 warehousey = 4;</code>
     */
    public Builder setWarehousey(int value) {
      bitField0_ |= 0x00000008;
      warehousey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 warehousey = 4;</code>
     */
    public Builder clearWarehousey() {
      bitField0_ = (bitField0_ & ~0x00000008);
      warehousey_ = 0;
      onChanged();
      return this;
    }

    private int destinationx_ ;
    /**
     * <code>required int32 destinationx = 5;</code>
     */
    public boolean hasDestinationx() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 destinationx = 5;</code>
     */
    public int getDestinationx() {
      return destinationx_;
    }
    /**
     * <code>required int32 destinationx = 5;</code>
     */
    public Builder setDestinationx(int value) {
      bitField0_ |= 0x00000010;
      destinationx_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 destinationx = 5;</code>
     */
    public Builder clearDestinationx() {
      bitField0_ = (bitField0_ & ~0x00000010);
      destinationx_ = 0;
      onChanged();
      return this;
    }

    private int destinationy_ ;
    /**
     * <code>required int32 destinationy = 6;</code>
     */
    public boolean hasDestinationy() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 destinationy = 6;</code>
     */
    public int getDestinationy() {
      return destinationy_;
    }
    /**
     * <code>required int32 destinationy = 6;</code>
     */
    public Builder setDestinationy(int value) {
      bitField0_ |= 0x00000020;
      destinationy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 destinationy = 6;</code>
     */
    public Builder clearDestinationy() {
      bitField0_ = (bitField0_ & ~0x00000020);
      destinationy_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object upsid_ = "";
    /**
     * <code>optional string upsid = 7;</code>
     */
    public boolean hasUpsid() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string upsid = 7;</code>
     */
    public java.lang.String getUpsid() {
      java.lang.Object ref = upsid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          upsid_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string upsid = 7;</code>
     */
    public com.google.protobuf.ByteString
        getUpsidBytes() {
      java.lang.Object ref = upsid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        upsid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string upsid = 7;</code>
     */
    public Builder setUpsid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      upsid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string upsid = 7;</code>
     */
    public Builder clearUpsid() {
      bitField0_ = (bitField0_ & ~0x00000040);
      upsid_ = getDefaultInstance().getUpsid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string upsid = 7;</code>
     */
    public Builder setUpsidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      upsid_ = value;
      onChanged();
      return this;
    }

    private long seqnum_ ;
    /**
     * <code>optional int64 seqnum = 8;</code>
     */
    public boolean hasSeqnum() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int64 seqnum = 8;</code>
     */
    public long getSeqnum() {
      return seqnum_;
    }
    /**
     * <code>optional int64 seqnum = 8;</code>
     */
    public Builder setSeqnum(long value) {
      bitField0_ |= 0x00000080;
      seqnum_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 seqnum = 8;</code>
     */
    public Builder clearSeqnum() {
      bitField0_ = (bitField0_ & ~0x00000080);
      seqnum_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object detail_ = "";
    /**
     * <code>optional string detail = 9;</code>
     */
    public boolean hasDetail() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string detail = 9;</code>
     */
    public java.lang.String getDetail() {
      java.lang.Object ref = detail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          detail_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string detail = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDetailBytes() {
      java.lang.Object ref = detail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        detail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string detail = 9;</code>
     */
    public Builder setDetail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      detail_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string detail = 9;</code>
     */
    public Builder clearDetail() {
      bitField0_ = (bitField0_ & ~0x00000100);
      detail_ = getDefaultInstance().getDetail();
      onChanged();
      return this;
    }
    /**
     * <code>optional string detail = 9;</code>
     */
    public Builder setDetailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      detail_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tutorial.ABookTruck)
  }

  // @@protoc_insertion_point(class_scope:tutorial.ABookTruck)
  private static final edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck();
  }

  public static edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ABookTruck>
      PARSER = new com.google.protobuf.AbstractParser<ABookTruck>() {
    @java.lang.Override
    public ABookTruck parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(
                builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ABookTruck> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ABookTruck> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.UPStoAmazon.ABookTruck getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

