// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: withAmazon.proto

package edu.duke.ece568.minUPS.protocol.UPStoAmazon;

public interface ABookTruckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.ABookTruck)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 packageid = 1;</code>
   */
  boolean hasPackageid();
  /**
   * <code>required int64 packageid = 1;</code>
   */
  long getPackageid();

  /**
   * <code>required int32 warehouseid = 2;</code>
   */
  boolean hasWarehouseid();
  /**
   * <code>required int32 warehouseid = 2;</code>
   */
  int getWarehouseid();

  /**
   * <code>required int32 warehousex = 3;</code>
   */
  boolean hasWarehousex();
  /**
   * <code>required int32 warehousex = 3;</code>
   */
  int getWarehousex();

  /**
   * <code>required int32 warehousey = 4;</code>
   */
  boolean hasWarehousey();
  /**
   * <code>required int32 warehousey = 4;</code>
   */
  int getWarehousey();

  /**
   * <code>required int32 destinationx = 5;</code>
   */
  boolean hasDestinationx();
  /**
   * <code>required int32 destinationx = 5;</code>
   */
  int getDestinationx();

  /**
   * <code>required int32 destinationy = 6;</code>
   */
  boolean hasDestinationy();
  /**
   * <code>required int32 destinationy = 6;</code>
   */
  int getDestinationy();

  /**
   * <code>optional string upsid = 7;</code>
   */
  boolean hasUpsid();
  /**
   * <code>optional string upsid = 7;</code>
   */
  java.lang.String getUpsid();
  /**
   * <code>optional string upsid = 7;</code>
   */
  com.google.protobuf.ByteString
      getUpsidBytes();

  /**
   * <code>optional int64 seqnum = 8;</code>
   */
  boolean hasSeqnum();
  /**
   * <code>optional int64 seqnum = 8;</code>
   */
  long getSeqnum();

  /**
   * <code>optional string detail = 9;</code>
   */
  boolean hasDetail();
  /**
   * <code>optional string detail = 9;</code>
   */
  java.lang.String getDetail();
  /**
   * <code>optional string detail = 9;</code>
   */
  com.google.protobuf.ByteString
      getDetailBytes();
}
