// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: withAmazon.proto

package edu.duke.ece568.minUPS.protocol.UPStoAmazon;

public interface AInformWorldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.AInformWorld)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 worldid = 1;</code>
   */
  boolean hasWorldid();
  /**
   * <code>required int64 worldid = 1;</code>
   */
  long getWorldid();
}
