// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: withAmazon.proto

package edu.duke.ece568.minUPS.protocol.UPStoAmazon;

public interface UDeliveredOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.UDelivered)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 packageid = 1;</code>
   */
  boolean hasPackageid();
  /**
   * <code>required int64 packageid = 1;</code>
   */
  long getPackageid();

  /**
   * <code>optional int64 seqnum = 2;</code>
   */
  boolean hasSeqnum();
  /**
   * <code>optional int64 seqnum = 2;</code>
   */
  long getSeqnum();
}
