// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: withAmazon.proto

package edu.duke.ece568.minUPS.protocol.UPStoAmazon;

public interface UReceivedWorldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.UReceivedWorld)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 worldid = 1;</code>
   */
  boolean hasWorldid();
  /**
   * <code>required int64 worldid = 1;</code>
   */
  long getWorldid();
}
