version: '2'

services:
  db:
    image: postgres:13.1
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=ups
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  proj:
    user: root
    build: .
    volumes:
      - .:/deploy
    ports:
      - "12345:12345"
      - "45678:45678"
    depends_on:
      - db