// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_ups.proto

package edu.duke.ece568.minUPS.protocol.UPStoWorld;

/**
 * Protobuf type {@code protocol.UCommands}
 */
public  final class UCommands extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocol.UCommands)
    UCommandsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UCommands.newBuilder() to construct.
  private UCommands(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UCommands() {
    pickups_ = java.util.Collections.emptyList();
    deliveries_ = java.util.Collections.emptyList();
    simspeed_ = 0;
    disconnect_ = false;
    queries_ = java.util.Collections.emptyList();
    acks_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.duke.ece568.minUPS.protocol.UPStoWorld.WorldUps.internal_static_protocol_UCommands_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.duke.ece568.minUPS.protocol.UPStoWorld.WorldUps.internal_static_protocol_UCommands_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands.class, edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands.Builder.class);
  }

  private int bitField0_;
  public static final int PICKUPS_FIELD_NUMBER = 1;
  private java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup> pickups_;
  /**
   * <code>repeated .protocol.UGoPickup pickups = 1;</code>
   */
  public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup> getPickupsList() {
    return pickups_;
  }
  /**
   * <code>repeated .protocol.UGoPickup pickups = 1;</code>
   */
  public java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickupOrBuilder> 
      getPickupsOrBuilderList() {
    return pickups_;
  }
  /**
   * <code>repeated .protocol.UGoPickup pickups = 1;</code>
   */
  public int getPickupsCount() {
    return pickups_.size();
  }
  /**
   * <code>repeated .protocol.UGoPickup pickups = 1;</code>
   */
  public edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup getPickups(int index) {
    return pickups_.get(index);
  }
  /**
   * <code>repeated .protocol.UGoPickup pickups = 1;</code>
   */
  public edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickupOrBuilder getPickupsOrBuilder(
      int index) {
    return pickups_.get(index);
  }

  public static final int DELIVERIES_FIELD_NUMBER = 2;
  private java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver> deliveries_;
  /**
   * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
   */
  public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver> getDeliveriesList() {
    return deliveries_;
  }
  /**
   * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
   */
  public java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliverOrBuilder> 
      getDeliveriesOrBuilderList() {
    return deliveries_;
  }
  /**
   * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
   */
  public int getDeliveriesCount() {
    return deliveries_.size();
  }
  /**
   * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
   */
  public edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver getDeliveries(int index) {
    return deliveries_.get(index);
  }
  /**
   * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
   */
  public edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliverOrBuilder getDeliveriesOrBuilder(
      int index) {
    return deliveries_.get(index);
  }

  public static final int SIMSPEED_FIELD_NUMBER = 3;
  private int simspeed_;
  /**
   * <code>optional uint32 simspeed = 3;</code>
   */
  public boolean hasSimspeed() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional uint32 simspeed = 3;</code>
   */
  public int getSimspeed() {
    return simspeed_;
  }

  public static final int DISCONNECT_FIELD_NUMBER = 4;
  private boolean disconnect_;
  /**
   * <code>optional bool disconnect = 4;</code>
   */
  public boolean hasDisconnect() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional bool disconnect = 4;</code>
   */
  public boolean getDisconnect() {
    return disconnect_;
  }

  public static final int QUERIES_FIELD_NUMBER = 5;
  private java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery> queries_;
  /**
   * <code>repeated .protocol.UQuery queries = 5;</code>
   */
  public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery> getQueriesList() {
    return queries_;
  }
  /**
   * <code>repeated .protocol.UQuery queries = 5;</code>
   */
  public java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UQueryOrBuilder> 
      getQueriesOrBuilderList() {
    return queries_;
  }
  /**
   * <code>repeated .protocol.UQuery queries = 5;</code>
   */
  public int getQueriesCount() {
    return queries_.size();
  }
  /**
   * <code>repeated .protocol.UQuery queries = 5;</code>
   */
  public edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery getQueries(int index) {
    return queries_.get(index);
  }
  /**
   * <code>repeated .protocol.UQuery queries = 5;</code>
   */
  public edu.duke.ece568.minUPS.protocol.UPStoWorld.UQueryOrBuilder getQueriesOrBuilder(
      int index) {
    return queries_.get(index);
  }

  public static final int ACKS_FIELD_NUMBER = 6;
  private java.util.List<java.lang.Long> acks_;
  /**
   * <code>repeated int64 acks = 6;</code>
   */
  public java.util.List<java.lang.Long>
      getAcksList() {
    return acks_;
  }
  /**
   * <code>repeated int64 acks = 6;</code>
   */
  public int getAcksCount() {
    return acks_.size();
  }
  /**
   * <code>repeated int64 acks = 6;</code>
   */
  public long getAcks(int index) {
    return acks_.get(index);
  }

  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocol.UCommands}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocol.UCommands)
      edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommandsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.duke.ece568.minUPS.protocol.UPStoWorld.WorldUps.internal_static_protocol_UCommands_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.duke.ece568.minUPS.protocol.UPStoWorld.WorldUps.internal_static_protocol_UCommands_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands.class, edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands.Builder.class);
    }

    // Construct using edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPickupsFieldBuilder();
        getDeliveriesFieldBuilder();
        getQueriesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (pickupsBuilder_ == null) {
        pickups_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        pickupsBuilder_.clear();
      }
      if (deliveriesBuilder_ == null) {
        deliveries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        deliveriesBuilder_.clear();
      }
      simspeed_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      disconnect_ = false;
      bitField0_ = (bitField0_ & ~0x00000008);
      if (queriesBuilder_ == null) {
        queries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        queriesBuilder_.clear();
      }
      acks_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.duke.ece568.minUPS.protocol.UPStoWorld.WorldUps.internal_static_protocol_UCommands_descriptor;
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands getDefaultInstanceForType() {
      return edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands.getDefaultInstance();
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands build() {
      edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands buildPartial() {
      edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands result = new edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (pickupsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          pickups_ = java.util.Collections.unmodifiableList(pickups_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.pickups_ = pickups_;
      } else {
        result.pickups_ = pickupsBuilder_.build();
      }
      if (deliveriesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          deliveries_ = java.util.Collections.unmodifiableList(deliveries_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.deliveries_ = deliveries_;
      } else {
        result.deliveries_ = deliveriesBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000001;
      }
      result.simspeed_ = simspeed_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000002;
      }
      result.disconnect_ = disconnect_;
      if (queriesBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          queries_ = java.util.Collections.unmodifiableList(queries_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.queries_ = queries_;
      } else {
        result.queries_ = queriesBuilder_.build();
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        acks_ = java.util.Collections.unmodifiableList(acks_);
        bitField0_ = (bitField0_ & ~0x00000020);
      }
      result.acks_ = acks_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    private int bitField0_;

    private java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup> pickups_ =
      java.util.Collections.emptyList();
    private void ensurePickupsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        pickups_ = new java.util.ArrayList<edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup>(pickups_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickupOrBuilder> pickupsBuilder_;

    /**
     * <code>repeated .protocol.UGoPickup pickups = 1;</code>
     */
    public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup> getPickupsList() {
      if (pickupsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(pickups_);
      } else {
        return pickupsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protocol.UGoPickup pickups = 1;</code>
     */
    public int getPickupsCount() {
      if (pickupsBuilder_ == null) {
        return pickups_.size();
      } else {
        return pickupsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protocol.UGoPickup pickups = 1;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup getPickups(int index) {
      if (pickupsBuilder_ == null) {
        return pickups_.get(index);
      } else {
        return pickupsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protocol.UGoPickup pickups = 1;</code>
     */
    public Builder setPickups(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup value) {
      if (pickupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePickupsIsMutable();
        pickups_.set(index, value);
        onChanged();
      } else {
        pickupsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UGoPickup pickups = 1;</code>
     */
    public Builder setPickups(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup.Builder builderForValue) {
      if (pickupsBuilder_ == null) {
        ensurePickupsIsMutable();
        pickups_.set(index, builderForValue.build());
        onChanged();
      } else {
        pickupsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UGoPickup pickups = 1;</code>
     */
    public Builder addPickups(edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup value) {
      if (pickupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePickupsIsMutable();
        pickups_.add(value);
        onChanged();
      } else {
        pickupsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UGoPickup pickups = 1;</code>
     */
    public Builder addPickups(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup value) {
      if (pickupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePickupsIsMutable();
        pickups_.add(index, value);
        onChanged();
      } else {
        pickupsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UGoPickup pickups = 1;</code>
     */
    public Builder addPickups(
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup.Builder builderForValue) {
      if (pickupsBuilder_ == null) {
        ensurePickupsIsMutable();
        pickups_.add(builderForValue.build());
        onChanged();
      } else {
        pickupsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UGoPickup pickups = 1;</code>
     */
    public Builder addPickups(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup.Builder builderForValue) {
      if (pickupsBuilder_ == null) {
        ensurePickupsIsMutable();
        pickups_.add(index, builderForValue.build());
        onChanged();
      } else {
        pickupsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UGoPickup pickups = 1;</code>
     */
    public Builder addAllPickups(
        java.lang.Iterable<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup> values) {
      if (pickupsBuilder_ == null) {
        ensurePickupsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pickups_);
        onChanged();
      } else {
        pickupsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UGoPickup pickups = 1;</code>
     */
    public Builder clearPickups() {
      if (pickupsBuilder_ == null) {
        pickups_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        pickupsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UGoPickup pickups = 1;</code>
     */
    public Builder removePickups(int index) {
      if (pickupsBuilder_ == null) {
        ensurePickupsIsMutable();
        pickups_.remove(index);
        onChanged();
      } else {
        pickupsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UGoPickup pickups = 1;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup.Builder getPickupsBuilder(
        int index) {
      return getPickupsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protocol.UGoPickup pickups = 1;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickupOrBuilder getPickupsOrBuilder(
        int index) {
      if (pickupsBuilder_ == null) {
        return pickups_.get(index);  } else {
        return pickupsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protocol.UGoPickup pickups = 1;</code>
     */
    public java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickupOrBuilder> 
         getPickupsOrBuilderList() {
      if (pickupsBuilder_ != null) {
        return pickupsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(pickups_);
      }
    }
    /**
     * <code>repeated .protocol.UGoPickup pickups = 1;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup.Builder addPickupsBuilder() {
      return getPickupsFieldBuilder().addBuilder(
          edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.UGoPickup pickups = 1;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup.Builder addPickupsBuilder(
        int index) {
      return getPickupsFieldBuilder().addBuilder(
          index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.UGoPickup pickups = 1;</code>
     */
    public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup.Builder> 
         getPickupsBuilderList() {
      return getPickupsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickupOrBuilder> 
        getPickupsFieldBuilder() {
      if (pickupsBuilder_ == null) {
        pickupsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickup.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoPickupOrBuilder>(
                pickups_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        pickups_ = null;
      }
      return pickupsBuilder_;
    }

    private java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver> deliveries_ =
      java.util.Collections.emptyList();
    private void ensureDeliveriesIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        deliveries_ = new java.util.ArrayList<edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver>(deliveries_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliverOrBuilder> deliveriesBuilder_;

    /**
     * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
     */
    public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver> getDeliveriesList() {
      if (deliveriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(deliveries_);
      } else {
        return deliveriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
     */
    public int getDeliveriesCount() {
      if (deliveriesBuilder_ == null) {
        return deliveries_.size();
      } else {
        return deliveriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver getDeliveries(int index) {
      if (deliveriesBuilder_ == null) {
        return deliveries_.get(index);
      } else {
        return deliveriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
     */
    public Builder setDeliveries(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver value) {
      if (deliveriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeliveriesIsMutable();
        deliveries_.set(index, value);
        onChanged();
      } else {
        deliveriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
     */
    public Builder setDeliveries(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver.Builder builderForValue) {
      if (deliveriesBuilder_ == null) {
        ensureDeliveriesIsMutable();
        deliveries_.set(index, builderForValue.build());
        onChanged();
      } else {
        deliveriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
     */
    public Builder addDeliveries(edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver value) {
      if (deliveriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeliveriesIsMutable();
        deliveries_.add(value);
        onChanged();
      } else {
        deliveriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
     */
    public Builder addDeliveries(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver value) {
      if (deliveriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeliveriesIsMutable();
        deliveries_.add(index, value);
        onChanged();
      } else {
        deliveriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
     */
    public Builder addDeliveries(
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver.Builder builderForValue) {
      if (deliveriesBuilder_ == null) {
        ensureDeliveriesIsMutable();
        deliveries_.add(builderForValue.build());
        onChanged();
      } else {
        deliveriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
     */
    public Builder addDeliveries(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver.Builder builderForValue) {
      if (deliveriesBuilder_ == null) {
        ensureDeliveriesIsMutable();
        deliveries_.add(index, builderForValue.build());
        onChanged();
      } else {
        deliveriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
     */
    public Builder addAllDeliveries(
        java.lang.Iterable<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver> values) {
      if (deliveriesBuilder_ == null) {
        ensureDeliveriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, deliveries_);
        onChanged();
      } else {
        deliveriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
     */
    public Builder clearDeliveries() {
      if (deliveriesBuilder_ == null) {
        deliveries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        deliveriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
     */
    public Builder removeDeliveries(int index) {
      if (deliveriesBuilder_ == null) {
        ensureDeliveriesIsMutable();
        deliveries_.remove(index);
        onChanged();
      } else {
        deliveriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver.Builder getDeliveriesBuilder(
        int index) {
      return getDeliveriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliverOrBuilder getDeliveriesOrBuilder(
        int index) {
      if (deliveriesBuilder_ == null) {
        return deliveries_.get(index);  } else {
        return deliveriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
     */
    public java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliverOrBuilder> 
         getDeliveriesOrBuilderList() {
      if (deliveriesBuilder_ != null) {
        return deliveriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(deliveries_);
      }
    }
    /**
     * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver.Builder addDeliveriesBuilder() {
      return getDeliveriesFieldBuilder().addBuilder(
          edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver.Builder addDeliveriesBuilder(
        int index) {
      return getDeliveriesFieldBuilder().addBuilder(
          index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.UGoDeliver deliveries = 2;</code>
     */
    public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver.Builder> 
         getDeliveriesBuilderList() {
      return getDeliveriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliverOrBuilder> 
        getDeliveriesFieldBuilder() {
      if (deliveriesBuilder_ == null) {
        deliveriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliver.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UGoDeliverOrBuilder>(
                deliveries_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        deliveries_ = null;
      }
      return deliveriesBuilder_;
    }

    private int simspeed_ ;
    /**
     * <code>optional uint32 simspeed = 3;</code>
     */
    public boolean hasSimspeed() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 simspeed = 3;</code>
     */
    public int getSimspeed() {
      return simspeed_;
    }
    /**
     * <code>optional uint32 simspeed = 3;</code>
     */
    public Builder setSimspeed(int value) {
      bitField0_ |= 0x00000004;
      simspeed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint32 simspeed = 3;</code>
     */
    public Builder clearSimspeed() {
      bitField0_ = (bitField0_ & ~0x00000004);
      simspeed_ = 0;
      onChanged();
      return this;
    }

    private boolean disconnect_ ;
    /**
     * <code>optional bool disconnect = 4;</code>
     */
    public boolean hasDisconnect() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool disconnect = 4;</code>
     */
    public boolean getDisconnect() {
      return disconnect_;
    }
    /**
     * <code>optional bool disconnect = 4;</code>
     */
    public Builder setDisconnect(boolean value) {
      bitField0_ |= 0x00000008;
      disconnect_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool disconnect = 4;</code>
     */
    public Builder clearDisconnect() {
      bitField0_ = (bitField0_ & ~0x00000008);
      disconnect_ = false;
      onChanged();
      return this;
    }

    private java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery> queries_ =
      java.util.Collections.emptyList();
    private void ensureQueriesIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        queries_ = new java.util.ArrayList<edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery>(queries_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery, edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UQueryOrBuilder> queriesBuilder_;

    /**
     * <code>repeated .protocol.UQuery queries = 5;</code>
     */
    public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery> getQueriesList() {
      if (queriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(queries_);
      } else {
        return queriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .protocol.UQuery queries = 5;</code>
     */
    public int getQueriesCount() {
      if (queriesBuilder_ == null) {
        return queries_.size();
      } else {
        return queriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .protocol.UQuery queries = 5;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery getQueries(int index) {
      if (queriesBuilder_ == null) {
        return queries_.get(index);
      } else {
        return queriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .protocol.UQuery queries = 5;</code>
     */
    public Builder setQueries(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery value) {
      if (queriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQueriesIsMutable();
        queries_.set(index, value);
        onChanged();
      } else {
        queriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UQuery queries = 5;</code>
     */
    public Builder setQueries(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery.Builder builderForValue) {
      if (queriesBuilder_ == null) {
        ensureQueriesIsMutable();
        queries_.set(index, builderForValue.build());
        onChanged();
      } else {
        queriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UQuery queries = 5;</code>
     */
    public Builder addQueries(edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery value) {
      if (queriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQueriesIsMutable();
        queries_.add(value);
        onChanged();
      } else {
        queriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UQuery queries = 5;</code>
     */
    public Builder addQueries(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery value) {
      if (queriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQueriesIsMutable();
        queries_.add(index, value);
        onChanged();
      } else {
        queriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UQuery queries = 5;</code>
     */
    public Builder addQueries(
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery.Builder builderForValue) {
      if (queriesBuilder_ == null) {
        ensureQueriesIsMutable();
        queries_.add(builderForValue.build());
        onChanged();
      } else {
        queriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UQuery queries = 5;</code>
     */
    public Builder addQueries(
        int index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery.Builder builderForValue) {
      if (queriesBuilder_ == null) {
        ensureQueriesIsMutable();
        queries_.add(index, builderForValue.build());
        onChanged();
      } else {
        queriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UQuery queries = 5;</code>
     */
    public Builder addAllQueries(
        java.lang.Iterable<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery> values) {
      if (queriesBuilder_ == null) {
        ensureQueriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, queries_);
        onChanged();
      } else {
        queriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UQuery queries = 5;</code>
     */
    public Builder clearQueries() {
      if (queriesBuilder_ == null) {
        queries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        queriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UQuery queries = 5;</code>
     */
    public Builder removeQueries(int index) {
      if (queriesBuilder_ == null) {
        ensureQueriesIsMutable();
        queries_.remove(index);
        onChanged();
      } else {
        queriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .protocol.UQuery queries = 5;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery.Builder getQueriesBuilder(
        int index) {
      return getQueriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .protocol.UQuery queries = 5;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UQueryOrBuilder getQueriesOrBuilder(
        int index) {
      if (queriesBuilder_ == null) {
        return queries_.get(index);  } else {
        return queriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .protocol.UQuery queries = 5;</code>
     */
    public java.util.List<? extends edu.duke.ece568.minUPS.protocol.UPStoWorld.UQueryOrBuilder> 
         getQueriesOrBuilderList() {
      if (queriesBuilder_ != null) {
        return queriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(queries_);
      }
    }
    /**
     * <code>repeated .protocol.UQuery queries = 5;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery.Builder addQueriesBuilder() {
      return getQueriesFieldBuilder().addBuilder(
          edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.UQuery queries = 5;</code>
     */
    public edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery.Builder addQueriesBuilder(
        int index) {
      return getQueriesFieldBuilder().addBuilder(
          index, edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery.getDefaultInstance());
    }
    /**
     * <code>repeated .protocol.UQuery queries = 5;</code>
     */
    public java.util.List<edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery.Builder> 
         getQueriesBuilderList() {
      return getQueriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery, edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UQueryOrBuilder> 
        getQueriesFieldBuilder() {
      if (queriesBuilder_ == null) {
        queriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery, edu.duke.ece568.minUPS.protocol.UPStoWorld.UQuery.Builder, edu.duke.ece568.minUPS.protocol.UPStoWorld.UQueryOrBuilder>(
                queries_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        queries_ = null;
      }
      return queriesBuilder_;
    }

    private java.util.List<java.lang.Long> acks_ = java.util.Collections.emptyList();
    private void ensureAcksIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        acks_ = new java.util.ArrayList<java.lang.Long>(acks_);
        bitField0_ |= 0x00000020;
       }
    }
    /**
     * <code>repeated int64 acks = 6;</code>
     */
    public java.util.List<java.lang.Long>
        getAcksList() {
      return java.util.Collections.unmodifiableList(acks_);
    }
    /**
     * <code>repeated int64 acks = 6;</code>
     */
    public int getAcksCount() {
      return acks_.size();
    }
    /**
     * <code>repeated int64 acks = 6;</code>
     */
    public long getAcks(int index) {
      return acks_.get(index);
    }
    /**
     * <code>repeated int64 acks = 6;</code>
     */
    public Builder setAcks(
        int index, long value) {
      ensureAcksIsMutable();
      acks_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 acks = 6;</code>
     */
    public Builder addAcks(long value) {
      ensureAcksIsMutable();
      acks_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 acks = 6;</code>
     */
    public Builder addAllAcks(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureAcksIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, acks_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 acks = 6;</code>
     */
    public Builder clearAcks() {
      acks_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocol.UCommands)
  }

  // @@protoc_insertion_point(class_scope:protocol.UCommands)
  private static final edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands();
  }

  public static edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<UCommands>
      PARSER = new com.google.protobuf.AbstractParser<UCommands>() {
    @java.lang.Override
    public UCommands parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(
                builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UCommands> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UCommands> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.duke.ece568.minUPS.protocol.UPStoWorld.UCommands getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

