// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_ups.proto

package edu.duke.ece568.minUPS.protocol.UPStoWorld;

public interface UConnectedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.UConnected)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 worldid = 1;</code>
   */
  boolean hasWorldid();
  /**
   * <code>required int64 worldid = 1;</code>
   */
  long getWorldid();

  /**
   * <code>required string result = 2;</code>
   */
  boolean hasResult();
  /**
   * <code>required string result = 2;</code>
   */
  java.lang.String getResult();
  /**
   * <code>required string result = 2;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
