// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_ups.proto

package edu.duke.ece568.minUPS.protocol.UPStoWorld;

public interface UDeliveryLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.UDeliveryLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 packageid = 1;</code>
   */
  boolean hasPackageid();
  /**
   * <code>required int64 packageid = 1;</code>
   */
  long getPackageid();

  /**
   * <code>required int32 x = 2;</code>
   */
  boolean hasX();
  /**
   * <code>required int32 x = 2;</code>
   */
  int getX();

  /**
   * <code>required int32 y = 3;</code>
   */
  boolean hasY();
  /**
   * <code>required int32 y = 3;</code>
   */
  int getY();
}
