// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_ups.proto

package edu.duke.ece568.minUPS.protocol.UPStoWorld;

public interface UErrOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.UErr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string err = 1;</code>
   */
  boolean hasErr();
  /**
   * <code>required string err = 1;</code>
   */
  java.lang.String getErr();
  /**
   * <code>required string err = 1;</code>
   */
  com.google.protobuf.ByteString
      getErrBytes();

  /**
   * <code>required int64 originseqnum = 2;</code>
   */
  boolean hasOriginseqnum();
  /**
   * <code>required int64 originseqnum = 2;</code>
   */
  long getOriginseqnum();

  /**
   * <code>required int64 seqnum = 3;</code>
   */
  boolean hasSeqnum();
  /**
   * <code>required int64 seqnum = 3;</code>
   */
  long getSeqnum();
}
