// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_ups.proto

package edu.duke.ece568.minUPS.protocol.UPStoWorld;

public interface UFinishedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.UFinished)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 truckid = 1;</code>
   */
  boolean hasTruckid();
  /**
   * <code>required int32 truckid = 1;</code>
   */
  int getTruckid();

  /**
   * <code>required int32 x = 2;</code>
   */
  boolean hasX();
  /**
   * <code>required int32 x = 2;</code>
   */
  int getX();

  /**
   * <code>required int32 y = 3;</code>
   */
  boolean hasY();
  /**
   * <code>required int32 y = 3;</code>
   */
  int getY();

  /**
   * <code>required string status = 4;</code>
   */
  boolean hasStatus();
  /**
   * <code>required string status = 4;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>required string status = 4;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>required int64 seqnum = 5;</code>
   */
  boolean hasSeqnum();
  /**
   * <code>required int64 seqnum = 5;</code>
   */
  long getSeqnum();
}
