// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: world_ups.proto

package edu.duke.ece568.minUPS.protocol.UPStoWorld;

public interface UQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.UQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 truckid = 1;</code>
   */
  boolean hasTruckid();
  /**
   * <code>required int32 truckid = 1;</code>
   */
  int getTruckid();

  /**
   * <code>required int64 seqnum = 2;</code>
   */
  boolean hasSeqnum();
  /**
   * <code>required int64 seqnum = 2;</code>
   */
  long getSeqnum();
}
